services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - recommender_net
    volumes:
      - ./data/:/app/data/
      - ./config/:/app/config/
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    networks:
      - recommender_net
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1g
    volumes:
      - ./config/:/app/config/

networks:
  recommender_net:
    driver: bridge
